"""Hyperparameter search spaces for training RwandaHealthEnv agents."""

from __future__ import annotations

from typing import Dict, List

# Ten curated configurations for each algorithm. Designed to balance sample
# efficiency and wall-clock constraints while remaining diverse enough for
# meaningful comparisons during tuning sessions.

DQN_SEARCH_SPACE: List[Dict[str, object]] = [
    {
        "learning_rate": 1.0e-3,
        "gamma": 0.95,
        "buffer_size": 60_000,
        "batch_size": 64,
        "train_freq": 4,
        "gradient_steps": 1,
        "target_update_interval": 500,
        "exploration_fraction": 0.25,
        "exploration_final_eps": 0.02,
        "learning_starts": 1_000,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 5.0e-4,
        "gamma": 0.99,
        "buffer_size": 100_000,
        "batch_size": 128,
        "train_freq": 8,
        "gradient_steps": 2,
        "target_update_interval": 1_000,
        "exploration_fraction": 0.2,
        "exploration_final_eps": 0.01,
        "learning_starts": 2_000,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 7.5e-4,
        "gamma": 0.98,
        "buffer_size": 80_000,
        "batch_size": 256,
        "train_freq": 4,
        "gradient_steps": 1,
        "target_update_interval": 750,
        "exploration_fraction": 0.15,
        "exploration_final_eps": 0.02,
        "learning_starts": 1_500,
        "policy_net_arch": [256, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 3.0e-4,
        "gamma": 0.97,
        "buffer_size": 50_000,
        "batch_size": 64,
        "train_freq": 1,
        "gradient_steps": 1,
        "target_update_interval": 500,
        "exploration_fraction": 0.3,
        "exploration_final_eps": 0.02,
        "learning_starts": 1_000,
        "policy_net_arch": [128, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 1.0e-4,
        "gamma": 0.99,
        "buffer_size": 120_000,
        "batch_size": 128,
        "train_freq": 16,
        "gradient_steps": 4,
        "target_update_interval": 1_500,
        "exploration_fraction": 0.1,
        "exploration_final_eps": 0.005,
        "learning_starts": 4_000,
        "policy_net_arch": [512, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 9.0e-4,
        "gamma": 0.96,
        "buffer_size": 70_000,
        "batch_size": 64,
        "train_freq": 4,
        "gradient_steps": 2,
        "target_update_interval": 600,
        "exploration_fraction": 0.25,
        "exploration_final_eps": 0.015,
        "learning_starts": 1_200,
        "policy_net_arch": [256, 256],
        "policy_activation": "elu",
        "ortho_init": False,
    },
    {
        "learning_rate": 4.0e-4,
        "gamma": 0.98,
        "buffer_size": 90_000,
        "batch_size": 256,
        "train_freq": 8,
        "gradient_steps": 4,
        "target_update_interval": 1_000,
        "exploration_fraction": 0.2,
        "exploration_final_eps": 0.01,
        "learning_starts": 2_500,
        "policy_net_arch": [256, 256, 128],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 6.0e-4,
        "gamma": 0.97,
        "buffer_size": 60_000,
        "batch_size": 128,
        "train_freq": 4,
        "gradient_steps": 2,
        "target_update_interval": 800,
        "exploration_fraction": 0.18,
        "exploration_final_eps": 0.02,
        "learning_starts": 1_800,
        "policy_net_arch": [256, 128],
        "policy_activation": "tanh",
        "ortho_init": False,
    },
    {
        "learning_rate": 8.0e-4,
        "gamma": 0.95,
        "buffer_size": 70_000,
        "batch_size": 64,
        "train_freq": 2,
        "gradient_steps": 1,
        "target_update_interval": 600,
        "exploration_fraction": 0.22,
        "exploration_final_eps": 0.02,
        "learning_starts": 1_200,
        "policy_net_arch": [128, 128],
        "policy_activation": "tanh",
        "ortho_init": False,
    },
    {
        "learning_rate": 2.0e-4,
        "gamma": 0.99,
        "buffer_size": 150_000,
        "batch_size": 256,
        "train_freq": 16,
        "gradient_steps": 4,
        "target_update_interval": 2_000,
        "exploration_fraction": 0.1,
        "exploration_final_eps": 0.01,
        "learning_starts": 5_000,
        "policy_net_arch": [512, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
]

PPO_SEARCH_SPACE: List[Dict[str, object]] = [
    {
        "learning_rate": 3.0e-4,
        "gamma": 0.99,
        "n_steps": 1_024,
        "batch_size": 256,
        "gae_lambda": 0.95,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 2.5e-4,
        "gamma": 0.98,
        "n_steps": 2_048,
        "batch_size": 256,
        "gae_lambda": 0.95,
        "clip_range": 0.2,
        "ent_coef": 0.005,
        "vf_coef": 0.4,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 1.0e-4,
        "gamma": 0.99,
        "n_steps": 1_536,
        "batch_size": 192,
        "gae_lambda": 0.97,
        "clip_range": 0.25,
        "ent_coef": 0.0,
        "vf_coef": 0.5,
        "max_grad_norm": 0.7,
        "policy_net_arch": [256, 256, 128],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 5.0e-4,
        "gamma": 0.97,
        "n_steps": 1_024,
        "batch_size": 128,
        "gae_lambda": 0.9,
        "clip_range": 0.2,
        "ent_coef": 0.02,
        "vf_coef": 0.4,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 256],
        "policy_activation": "tanh",
        "ortho_init": False,
    },
    {
        "learning_rate": 7.0e-4,
        "gamma": 0.98,
        "n_steps": 2_048,
        "batch_size": 512,
        "gae_lambda": 0.92,
        "clip_range": 0.15,
        "ent_coef": 0.005,
        "vf_coef": 0.6,
        "max_grad_norm": 0.5,
        "policy_net_arch": [512, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 3.0e-4,
        "gamma": 0.99,
        "n_steps": 768,
        "batch_size": 128,
        "gae_lambda": 0.95,
        "clip_range": 0.2,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 128],
        "policy_activation": "elu",
        "ortho_init": False,
    },
    {
        "learning_rate": 2.0e-4,
        "gamma": 0.995,
        "n_steps": 2_048,
        "batch_size": 256,
        "gae_lambda": 0.97,
        "clip_range": 0.2,
        "ent_coef": 0.0,
        "vf_coef": 0.5,
        "max_grad_norm": 0.7,
        "policy_net_arch": [256, 256],
        "policy_activation": "tanh",
        "ortho_init": True,
    },
    {
        "learning_rate": 4.0e-4,
        "gamma": 0.98,
        "n_steps": 1_280,
        "batch_size": 256,
        "gae_lambda": 0.93,
        "clip_range": 0.3,
        "ent_coef": 0.01,
        "vf_coef": 0.4,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 6.0e-4,
        "gamma": 0.97,
        "n_steps": 1_024,
        "batch_size": 256,
        "gae_lambda": 0.95,
        "clip_range": 0.25,
        "ent_coef": 0.015,
        "vf_coef": 0.5,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 1.5e-4,
        "gamma": 0.99,
        "n_steps": 1_536,
        "batch_size": 256,
        "gae_lambda": 0.96,
        "clip_range": 0.2,
        "ent_coef": 0.0,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "policy_net_arch": [256, 256, 128],
        "policy_activation": "tanh",
        "ortho_init": True,
    },
]

A2C_SEARCH_SPACE: List[Dict[str, object]] = [
    {
        "learning_rate": 7.0e-4,
        "gamma": 0.99,
        "n_steps": 5,
        "gae_lambda": 0.95,
        "ent_coef": 0.01,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": True,
    },
    {
        "learning_rate": 5.0e-4,
        "gamma": 0.98,
        "n_steps": 8,
        "gae_lambda": 0.9,
        "ent_coef": 0.005,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 3.0e-4,
        "gamma": 0.995,
        "n_steps": 5,
        "gae_lambda": 0.96,
        "ent_coef": 0.0,
        "vf_coef": 0.6,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 256, 128],
        "policy_activation": "tanh",
        "ortho_init": True,
    },
    {
        "learning_rate": 9.0e-4,
        "gamma": 0.97,
        "n_steps": 10,
        "gae_lambda": 0.92,
        "ent_coef": 0.015,
        "vf_coef": 0.4,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 4.0e-4,
        "gamma": 0.98,
        "n_steps": 5,
        "gae_lambda": 0.95,
        "ent_coef": 0.005,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [128, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 6.0e-4,
        "gamma": 0.99,
        "n_steps": 8,
        "gae_lambda": 0.97,
        "ent_coef": 0.0,
        "vf_coef": 0.5,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 256],
        "policy_activation": "elu",
        "ortho_init": True,
    },
    {
        "learning_rate": 2.0e-4,
        "gamma": 0.995,
        "n_steps": 10,
        "gae_lambda": 0.95,
        "ent_coef": 0.002,
        "vf_coef": 0.6,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 128],
        "policy_activation": "tanh",
        "ortho_init": True,
    },
    {
        "learning_rate": 8.0e-4,
        "gamma": 0.97,
        "n_steps": 5,
        "gae_lambda": 0.9,
        "ent_coef": 0.02,
        "vf_coef": 0.4,
        "max_grad_norm": 0.5,
        "policy_net_arch": [256, 256],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 1.0e-3,
        "gamma": 0.96,
        "n_steps": 8,
        "gae_lambda": 0.9,
        "ent_coef": 0.02,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "policy_net_arch": [128, 128],
        "policy_activation": "relu",
        "ortho_init": False,
    },
    {
        "learning_rate": 3.5e-4,
        "gamma": 0.99,
        "n_steps": 5,
        "gae_lambda": 0.96,
        "ent_coef": 0.0,
        "vf_coef": 0.5,
        "max_grad_norm": 0.6,
        "policy_net_arch": [256, 256, 128],
        "policy_activation": "tanh",
        "ortho_init": True,
    },
]

REINFORCE_SEARCH_SPACE: List[Dict[str, object]] = [
    {
        "learning_rate": 1.0e-3,
        "gamma": 0.99,
        "hidden_layers": [256, 256],
        "entropy_coef": 0.001,
        "normalize_returns": True,
        "episodes": 400,
        "batch_episodes": 1,
        "max_grad_norm": 0.5,
    },
    {
        "learning_rate": 5.0e-4,
        "gamma": 0.98,
        "hidden_layers": [256, 128],
        "entropy_coef": 0.0,
        "normalize_returns": True,
        "episodes": 300,
        "batch_episodes": 2,
        "max_grad_norm": 0.5,
    },
    {
        "learning_rate": 8.0e-4,
        "gamma": 0.97,
        "hidden_layers": [128, 128],
        "entropy_coef": 0.002,
        "normalize_returns": False,
        "episodes": 350,
        "batch_episodes": 2,
        "max_grad_norm": 0.6,
    },
    {
        "learning_rate": 3.0e-4,
        "gamma": 0.99,
        "hidden_layers": [256, 256, 128],
        "entropy_coef": 0.0,
        "normalize_returns": True,
        "episodes": 450,
        "batch_episodes": 1,
        "max_grad_norm": 0.6,
    },
    {
        "learning_rate": 6.0e-4,
        "gamma": 0.98,
        "hidden_layers": [256, 256],
        "entropy_coef": 0.001,
        "normalize_returns": True,
        "episodes": 500,
        "batch_episodes": 3,
        "max_grad_norm": 0.5,
    },
    {
        "learning_rate": 1.2e-3,
        "gamma": 0.96,
        "hidden_layers": [128, 128],
        "entropy_coef": 0.003,
        "normalize_returns": False,
        "episodes": 320,
        "batch_episodes": 2,
        "max_grad_norm": 0.7,
    },
    {
        "learning_rate": 4.0e-4,
        "gamma": 0.995,
        "hidden_layers": [256, 128],
        "entropy_coef": 0.0,
        "normalize_returns": True,
        "episodes": 480,
        "batch_episodes": 2,
        "max_grad_norm": 0.6,
    },
    {
        "learning_rate": 9.0e-4,
        "gamma": 0.97,
        "hidden_layers": [256, 256],
        "entropy_coef": 0.002,
        "normalize_returns": True,
        "episodes": 360,
        "batch_episodes": 1,
        "max_grad_norm": 0.6,
    },
    {
        "learning_rate": 7.0e-4,
        "gamma": 0.99,
        "hidden_layers": [256, 256],
        "entropy_coef": 0.0015,
        "normalize_returns": True,
        "episodes": 420,
        "batch_episodes": 2,
        "max_grad_norm": 0.5,
    },
    {
        "learning_rate": 2.5e-4,
        "gamma": 0.995,
        "hidden_layers": [256, 256, 128],
        "entropy_coef": 0.0,
        "normalize_returns": True,
        "episodes": 600,
        "batch_episodes": 3,
        "max_grad_norm": 0.6,
    },
]

__all__ = [
    "DQN_SEARCH_SPACE",
    "PPO_SEARCH_SPACE",
    "A2C_SEARCH_SPACE",
    "REINFORCE_SEARCH_SPACE",
]
